version: '3.5'

services:
  nginx:
    build:
      context: .
    ports:
      - ${EXPOSE_NGINX_PORT}:8002
      - ${EXPOSE_NGINX_RTMP_PORT}:1935
    env_file: ./.env
    networks:
      - default
      - default_external

networks:
  default_external:
    external:
      name: default_external
